---
- hosts: pcshosts
  become: yes
  gather_facts: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install webserver
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"
 
  - name: i want to copy file from one to another floder
    copy:
     src: mystatic.txt
     dest: /home/ubuntu/mystatic.txt