---
- hosts: pcshosts
  become: yes
  gather_facts: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install webserver
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"
