---
- hosts: pcshosts
  become: yes
  gather_facts: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
    notify: restart webserver
 
  - name: i want to copy file from one to another floder
    copy:
      src: mystatic.txt
      dest: /home/ubuntu/mystatic.txt
    notify: restart webserver
    
  - name: i want to change index page by creating a file2
    template:
     src: index.j2
     dest: /var/www/html/index.html

  - name: i want to install tree
    apt:
      name: tree
      state: present
    notify: restart webserver
    

  handlers:
   - name:  restart webserver
     service:
       name: apache2
       state: restarted 
