---
- hosts: all
  become: yes
  tasks:
  - name: yo install git
    apt:
     name: git
     state: present

  - name: i want to install wget
    apt:
     name: wget
     state: present
  
  
  
  

