---
- hosts: pcshosts
  become: yes
  gather_facts: yes
  tasks:
  - name: yo install apache2 on my ubuntu2
    apt:
     name: "{{mywebpackonubuntu}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: i want to start aache2 on my ubuntu2
    service:
     name: "{{mywebpackonubuntu}}"
     state: started 
    when: ansible_os_family=="Debian"

  - name: i will install webserver on my redhat server 
    yum:
     name: "{{mywebpackonRedHat}}"
     state: present 
    when: ansible_os_family=="RedHat"

  - name: i want to start aache2 on my ubuntu2
    service:
     name: "{{mywebpackonRedHat}}"
     state: started
    when: ansible_os_family=="RedHat"
  